package domain

type Record struct {
	Id                            int    `json:"id"`
	Uid                           string `json:"uid"`
	Domain                        string `json:"domain"`
	Cn                            string `json:"cn"`
	Department                    string `json:"department"`
	Title                         string `json:"title"`
	Who                           string `json:"who"`
	Logon_count                   int    `json:"logon_count"`
	Num_logons7                   int    `json:"num_logons7"`
	Num_share7                    int    `json:"num_share7"`
	Num_file7                     int    `json:"num_file7"`
	Num_ad7                       int    `json:"num_ad7"`
	Num_n7                        int    `json:"num_n7"`
	Num_logons14                  int    `json:"num_logons14"`
	Num_share14                   int    `json:"num_share14"`
	Num_file14                    int    `json:"num_file14"`
	Num_ad14                      int    `json:"num_ad14"`
	Num_n14                       int    `json:"num_n14"`
	Num_logons30                  int    `json:"num_logons30"`
	Num_share30                   int    `json:"num_share30"`
	Num_file30                    int    `json:"num_file30"`
	Num_ad30                      int    `json:"num_ad30"`
	Num_n30                       int    `json:"num_n30"`
	Num_logons150                 int    `json:"num_logons150"`
	Num_share150                  int    `json:"num_share150"`
	Num_file150                   int    `json:"num_file150"`
	Num_ad150                     int    `json:"num_ad150"`
	Num_n150                      int    `json:"num_n150"`
	Num_logons365                 int    `json:"num_logons365"`
	Num_share365                  int    `json:"num_share365"`
	Num_file365                   int    `json:"num_file365"`
	Num_ad365                     int    `json:"num_ad365"`
	Num_n365                      int    `json:"num_n365"`
	Has_user_principal_name       int    `json:"has_user_principal_name"`
	Has_mail                      int    `json:"has_mail"`
	Has_phone                     int    `json:"has_phone"`
	Flag_disabled                 int    `json:"flag_disabled"`
	Flag_lockout                  int    `json:"flag_lockout"`
	Flag_password_not_required    int    `json:"flag_password_not_required"`
	Flag_password_cant_change     int    `json:"flag_password_cant_change"`
	Flag_dont_expire_password     int    `json:"flag_dont_expire_password"`
	Owned_files                   int    `json:"owned_files"`
	Num_mailboxes                 int    `json:"num_mailboxes"`
	Num_member_of_groups          int    `json:"num_member_of_groups"`
	Num_member_of_indirect_groups int    `json:"num_member_of_indirect_groups"`
	Member_of_indirect_groups_ids []int  `json:"member_of_indirect_groups_ids"`
	Member_of_groups_ids          []int  `json:"member_of_groups_ids"`
	Is_admin                      int    `json:"is_admin"`
	Is_service                    int    `json:"is_service"`
}
